injury:
  armor_pieces_for_immunity:
    - adventurecraft:copper_helmet
    - adventurecraft:copper_chestplate
    - adventurecraft:copper_leggings
    - adventurecraft:copper_boots
  bandage_relief: 35.0

disease:
  armor_pieces_for_immunity:
    - adventurecraft:copper_helmet
    - adventurecraft:copper_chestplate
    - adventurecraft:copper_leggings
    - adventurecraft:copper_boots
  medicine_relief: 55.0
