injury:
  armor_pieces_for_immunity:
    - adventurecraft:copper_helmet
    - adventurecraft:copper_chestplate
    - adventurecraft:copper_leggings
    - adventurecraft:copper_boots

disease:
  armor_pieces_for_immunity:
    - adventurecraft:copper_helmet
    - adventurecraft:copper_chestplate
    - adventurecraft:copper_leggings
    - adventurecraft:copper_boots
